I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 278, in script
    python:
ScriptError: could not find label 'start'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "/usr/share/renpy/renpy/bootstrap.py", line 277, in bootstrap
    renpy.main.main()
  File "/usr/share/renpy/renpy/main.py", line 660, in main
    run(restart)
  File "/usr/share/renpy/renpy/main.py", line 146, in run
    renpy.execution.run_context(True)
  File "/usr/share/renpy/renpy/execution.py", line 938, in run_context
    context.run()
  File "renpy/common/00start.rpy", line 278, in script
    python:
  File "/usr/share/renpy/renpy/script.py", line 927, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'start'.

Linux-6.2.0-63.fc38.x86_64-x86_64-with-glibc2.37 x86_64
Ren'Py 8.0.3.0
MadokaVN2 1.0
Thu Mar  9 20:00:54 2023
